src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_At = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_At = null;

    #[ORM\Column(nullable: true)]
    private ?int $reportedCount = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isFlagged = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isApproved = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isDeleted = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Post $post = null;

    #[ORM\ManyToOne(targetEntity: "User")]
    #[ORM\JoinColumn(name: "id", referencedColumnName: "id_user")]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_At;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_At): static
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_At;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_At): static
    {
        $this->updated_At = $updated_At;

        return $this;
    }

    public function getReportedCount(): ?int
    {
        return $this->reportedCount;
    }

    public function setReportedCount(?int $reportedCount): static
    {
        $this->reportedCount = $reportedCount;

        return $this;
    }

    public function isIsFlagged(): ?bool
    {
        return $this->isFlagged;
    }

    public function setIsFlagged(?bool $isFlagged): static
    {
        $this->isFlagged = $isFlagged;

        return $this;
    }

    public function isIsApproved(): ?bool
    {
        return $this->isApproved;
    }

    public function setIsApproved(?bool $isApproved): static
    {
        $this->isApproved = $isApproved;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(?bool $isDeleted): static
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): static
    {
        $this->post = $post;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setUpdatedAt(new \DateTimeImmutable() );
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->setUpdatedAt(new \DateTimeImmutable() );
    }
}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Service\BadWordFilter;
use App\Entity\Post;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use App\Repository\PostRepository;
use ConsoleTVs\Profanity\Facades\Profanity;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\EventDispatcher\Event;

#[Route('/commentaire')]
class CommentaireController extends AbstractController
{
    #[Route('/', name: 'app_commentaire_index', methods: ['GET'])]
    public function index(CommentaireRepository $commentaireRepository,EntityManagerInterface $entityManager): Response
    {
        $commentaires = $commentaireRepository->findAll();
        foreach ($commentaires as $commentaire) {
            if ($commentaire->getReportedCount() >= 5) {
                $commentaire->setIsFlagged(true);
                $entityManager->flush();
            }else
            $commentaire->setIsFlagged(false);
        }
        return $this->render('commentaire/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commentaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,BadWordFilter $badWordFilter): Response
    {


        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentaire->setReportedCount(0);
            $commentaire->setIsApproved(false);
            $commentaire->setIsDeleted(false);
            $commentaire->setIsFlagged(false);

            $commentaire->setContent($badWordFilter->filter($commentaire->getContent()));
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentaire/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/new/{id}', name: 'app_commentairePost_new', methods: ['GET', 'POST'])]
    public function newCommentPost(Post $id,Request $request, EntityManagerInterface $entityManager): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentaire->setReportedCount(0);
            $commentaire->setIsApproved(false);
            $commentaire->setIsDeleted(false);
            $commentaire->setIsFlagged(false);
            $commentaire->setPost($id);


            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentaire/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commentaire_show', methods: ['GET'])]
    public function show(Commentaire $commentaire): Response
    {
        return $this->render('commentaire/show.html.twig', [
            'commentaire' => $commentaire,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commentaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentaire/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/report', name: 'app_commentaire_report', methods: ['GET', 'POST'])]
    public function report(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        $commentaire->setReportedCount($commentaire->getReportedCount()+1);
        $entityManager->flush();
        return $this->redirectToRoute('app_post_comments', ['postid' => $commentaire->getPost()->getId()] , Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_commentaire_delete', methods: ['POST'])]
    public function delete(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
    }

//    /**
//     * @Route("/getEvents/{eventId}", name="comments_by_event")
//     */
//    public function getCommentsByEventId($eventId,CommentaireRepository $commentaireRepo , PostRepository $postRepo): Response
//    {
//        $event = $postRepo->find($eventId);
//
//        if (!$event) {
//            throw $this->createNotFoundException('Event not found');
//        }
//
//        // Fetch comments associated with the event
//        $comments = $commentaireRepo->findCommentsByEventId(['event' => $event]);
//
//        return $this->render('commentaire/index.html.twig', [
//            'event' => $event,
//            'commentaire' => $comments,
//        ]);
//    }
}

templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('app_commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="button" style="background-color: deeppink">Delete</button>
</form>

templates/commentaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
    <h1>Commentaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Created_At</th>
                <th>Updated_At</th>
                <th>ReportedCount</th>
                <th>IsFlagged</th>
                <th>IsApproved</th>
                <th>IsDeleted</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.content }}</td>
                <td>{{ commentaire.createdAt ? commentaire.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commentaire.updatedAt ? commentaire.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commentaire.reportedCount }}</td>
                <td>{{ commentaire.isFlagged ? 'Yes' : 'No' }}</td>
                <td>{{ commentaire.isApproved ? 'Yes' : 'No' }}</td>
                <td>{{ commentaire.isDeleted ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_commentaire_show', {'id': commentaire.id}) }}">show</a>
                    <a href="{{ path('app_commentaire_edit', {'id': commentaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commentaire_new') }}">Create new</a>
{% endblock %}

templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
<div class="w3-content" style="max-width:900px;margin:400px;margin-top: 50px">
    <!-- Grid -->
    <div class="w3-row">
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('app_commentaire_index') }}">back to list</a>
    </div>
</div>
{% endblock %}

templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ commentaire.content }}</td>
            </tr>
            <tr>
                <th>Created_At</th>
                <td>{{ commentaire.createdAt ? commentaire.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_At</th>
                <td>{{ commentaire.updatedAt ? commentaire.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ReportedCount</th>
                <td>{{ commentaire.reportedCount }}</td>
            </tr>
            <tr>
                <th>IsFlagged</th>
                <td>{{ commentaire.isFlagged ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>IsApproved</th>
                <td>{{ commentaire.isApproved ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>IsDeleted</th>
                <td>{{ commentaire.isDeleted ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commentaire_index') }}">back to list</a>

    <a href="{{ path('app_commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}